### ISSUE TITLE
Document how to run against local lists

### ISSUE THREAD

**Issue by mgifford** [GovTechSG/purple-hats#10]
From this:

  1. A text file with a list of links
  2. A XML file with XML tags in Sitemap Protocol format

It sounds like I should be able to run this against a local file on my local system, but I can't seem to get the formatting to accept a local path. 

Closest I can come gives me this error:

```
Scanning website...
(node:76046) UnhandledPromiseRejectionWarning: Error: Cannot fetch a request list from file:/Users/mikegifford/purple-hats/url_list_Olivero.xml: RequestError: Error: Invalid URI "file:///Users/mikegifford/purple-hats/url_list_Olivero.xml"
    at RequestList._fetchRequestsFromUrl (/Users/mikegifford/purple-hats/node_modules/apify/build/request_list.js:564:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at evalScript (internal/bootstrap/node.js:585:13)
    at startup (internal/bootstrap/node.js:267:9)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
(node:76046) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:76046) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
The file /Users/mikegifford/purple-hats/results/2020-9-10/159975560855e6613c80/reports/report.html does not exist.
```

**Comment by younglim** [comment]
This is addressed in:
- sitemap.txt https://github.com/GovTechSG/purple-hats/issues/56
- sitemap.xml https://github.com/GovTechSG/purple-hats/issues/54
